### ISSUE TITLE
make:twc:form - Class not found

### ISSUE THREAD

**Issue by thedevopser** [thewalkingcoder/maker-bundle#1]
Lors de la génération d'un formulaire par le bundle, si on veux ajouter une entité ou une classe au formulaire, on se retrouve avec une erreur de type `Class xxx does not exist`

Le bundle rajoute automatiquement `App\Entity` au début du namespace que l'on a ajouté

![image](https://user-images.githubusercontent.com/6714527/104893711-0f239280-5974-11eb-80b2-df72b55fcefe.png)

**Comment by thewalkingcoder** [comment]
@Gothdroid33 use `\App\Import\Domain\Entity\Facturation` instead
