### ISSUE TITLE
[7.x-dev] - Entity generator

### ISSUE THREAD

**Issue by thedevopser** [thewalkingcoder/maker-bundle#3]
Hi

There is a bug when we try to use the entity generator on Symfony 7 (I use the 7.x-dev branch)

![image](https://github.com/user-attachments/assets/50def807-a620-404c-b328-5e64f812f7a5)

```
Warning: Undefined variable $id_type
```

**Comment by thewalkingcoder** [comment]
@thedevopser thank for report.

it's fix now.

Just change on your `composer.json`

```yaml
"twc/maker-bundle": "^7.0"
```
and try 

```yaml
composer update
```

For better maintenance, branch 7.x is now only for symfony 7.x.
